---
- hosts: ec2-52-3-251-143.compute-1.amazonaws.com
  become: true
  become_method: sudo
  tasks:
   - name : run date command
     shell: "date"

   - name : file module
     shell: "mkdir -p /opt/ansible/a"
 
