---
- hosts: ec2-3-84-227-3.compute-1.amazonaws.com
  become: true
  become_method: sudo
  tasks:
   - name : run date command
     shell: "date"

   - name : file module
     shell: "mkdir -p /opt/ansible/b"
 
