---
- name : install open jdk
  yum :
   name : 
     - java-1.8.0-openjdk
     - java-1.8.0-openjdk-devel
- name : tomcat war file
  get_url:
    url: https://mirrors.estointernet.in/apache/tomcat/tomcat-8/v8.5.60/bin/apache-tomcat-8.5.60.tar.gz
    dest: /opt/
    
- name : untar
  shell: tar -xzvf /opt/apache-tomcat-8.5.60.tar.gz -C /opt/tomcat/ --strip-components=1
- name: create tomcat group
  group: name=tomcat state=present

- name: create tomcat user
  user: name=tomcat group=tomcat state=present shell=/bin/bash home=/home/tomcat createhome=yes
  
- name : chmod
  shell: chmod -R 755 /opt/tomcat

- name : chown
  shell: "chown -R tomcat:tomcat /opt/tomcat"  
  
- name : tomcat serviece file
  get_url:
    url: https://devops2020.s3.amazonaws.com/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
- name : enable the service
  shell: "systemctl enable tomcat"
  
- name : daemon reload
  shell: "systemctl daemon-reload"
 
- name : start the tomcat 
  shell: "systemctl start tomcat"
