---


- name : stop tomcat
  shell: "systemctl stop tomcat"
  
- name : Get the war file from artifactory
  get_url:
     url: "{{jfrogurl}}/artifactory/{{jfrogpath1.dev}}/test-web/sample-1.10.20.war"
     dest: /tmp/
     username: "balaji2003engg@gmail.com"
     password: "{{jfrogpassword}}"
     
- name : copy the war to the webapps folder
  copy:
     src: /tmp/sample-1.10.20.war
     dest: /opt/tomcat/webapps/sample
     remote_src: yes
- name : pwd
  shell: "pwd" 
- debug : env  
- name : env variabke
  
- name : copy the tomcat service file 
  copy:
    src: "roles/tomcat/templatestomcat.service.j2"
    dest: "/etc/systemd/system/tomcat.servcie"
    remote_src: yes

- name : enable the service
  shell: "systemctl enable tomcat"
  
- name : daemon reload
  shell: "systemctl daemon-reload"
 
- name : start the tomcat 
  shell: "systemctl start tomcat"
