---


- name : stop tomcat
  shell: "systemctl stop tomcat"
  
- name : Get the war file from artifactory
  get_url:
     url: "{{jfrogurl}}/artifactory/libs-snapshot-local/test-web/sample-1.10.20.war"
     dest: /tmp/
     username: "balaji2003engg@gmail.com"
     password: "{{jfrogpassword}}"
     
- name : copy the war to the webapps folder
  copy:
     src: /tmp/sample-1.10.20.war
     dest: /opt/tomcat/webapps
     remote_src: true
      
- name : start the tomcat 
  shell: "systemctl start tomcat"
